name: Feature CI

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - feature/*

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Biome Check
        run: bun run biome:check

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Upload to S3
        if: ${{ github.ref_name == 'main' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build output to S3
        if: ${{ github.ref_name == 'main' }}
        run: aws s3 sync ./out s3://npi-test-11011/
